### ISSUE TITLE
Allow multiple requests?

### ISSUE THREAD

**Issue by ghost** [CCLA-Will-Check/ccla-wills#12]
Do we need to allow users to request multiple testator/will information in a single session? Currently, I'm operating on the assumption that a user is just looking for one will, so a web form is fine; if people want to make multiple requests at once, should they be able to do that in a single screen? Or upload a file to do a batch of requests?

**Comment by smockeh** [comment]
I don't think we need to allow multiple requests; I think it would be extremely rare for that to happen so a web form should be fine.

**Comment by ghost** [comment]
Perfect!
