### ISSUE TITLE
Do you want to keep or delete old/fulfilled requests?

### ISSUE THREAD

**Issue by ghost** [CCLA-Will-Check/ccla-wills#20]

**Comment by smockeh** [comment]
I think it would be useful for us to keep them / archive them for stats purposes. Would there be an easy way to add a flag that we could say Open / In Progress / Complete ? So we could hide the completed ones but still have access to them if need be.

**Comment by ghost** [comment]
Yes, I can do that - I'll add the field, then there will be a way to filter the ones you want to look at.
