### ISSUE TITLE
How should duplicate/problem wills be handled?

### ISSUE THREAD

**Issue by ghost** [CCLA-Will-Check/ccla-wills#21]
Should lawyers be responsible for deleting/fixing duplicate or records with errors? This would mean giving them search, edit, and delete functionality within the system.

**Comment by smockeh** [comment]
I think we'd rather not have them have that level of access. At the beginning there shouldn't be too much for us to handle. Maybe there should be a Year of Will field on the Register form as well? That might help differentiate if one person is making multiple wills.

**Comment by ghost** [comment]
Sounds good - I can add a "year of will" field.
