### ISSUE TITLE
Application doesn't do anything with an uploaded CSV

### ISSUE THREAD

**Issue by ghost** [CCLA-Will-Check/ccla-wills#41]
Ideally, it would parse the content into the database. Rake task?

Actually, @smockeh - do you want an uploaded CSV to be added to the database without vetting? Or do you want to take a look at the data before it gets added, in case someone tries to upload, say, 100 wills but the data is wrong...? Thoughts?

**Comment by smockeh** [comment]
Yeah I think we'd want to vet it first. Ideally we'd like an "approved" toggle / queue for all of them that are added before they go into the database, including the .csv ones (batch approve?). But if that's too hard don't worry about it for now!

**Comment by ghost** [comment]
Hmm. They have to go into a database first, even in order to be marked as "approved" or not. Let me think about this...

**Comment by smockeh** [comment]
Would it be possible that everything goes into the database, but only approved records show up in search/browse results?

**Comment by CCLA-Will-Check** [comment]
I forgot that this *does* actually load the wills into the database. I've set it so that it flags these wills as "not approved."
