### ISSUE TITLE
Remaining fixes.

### ISSUE THREAD

**Issue by ghost** [CCLA-Will-Check/ccla-wills#52]
- [x] #10 of the FAQ has been revised and should read: Est-ce c'est disponible en français?
Will Check n'est présentement pas disponible en français. Nous espérons de le rendre bilingue à l'avenir. (Is "Est-ce c'est" right? AFAIK, "Est-ce" or "Est-ce que c'est" would both be correct...)
- [x] On the Contact page, link “info@ccla-abcc.ca” as a mailto email.

**Comment by smockeh** [comment]
Oops, yeah you're right. Use Est-ce que c'est!

**Comment by ghost** [comment]
- [x] We’ve had some feedback that City / Place / Country of Birth are not commonly collected information from clients. Could we make them non-mandatory fields for both registering and finding?

**Comment by ghost** [comment]
- [x] I believe we’d like Date of Birth to be optional on registering as well.
