### ISSUE TITLE
Searching

### ISSUE THREAD

**Issue by smockeh** [CCLA-Will-Check/ccla-wills#57]
Could we make the default search not search the lawyer's name and lawyer's info? ie. By currently searching Gauthier it comes up with everything that MJ Gauthier has submitted, instead of just the Wills with that name. Ideally it should not hit on Lawyer / Firm / LSUC# / Telephone Number or Date Created.

**Comment by ghost** [comment]
Taking those fields out is done; do you think you need another way to pull up the wills for a particular lawyer/firm? I.e should I add a second search screen for that kind of search?

**Comment by smockeh** [comment]
Nah, probably not needed for now. Thanks!
